version: "3.7"
#
services:
  #
  db:
    container_name: postgres_db 
    build: 
        dockerfile: db.dockerfile
        context: ./Scripts
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "40000:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back-tier
  #
  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3.7-management-alpine
    restart: always
    networks:
      - back-tier
    ports:
      - "13028:5672" 
      - "13038:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  #
  company_api:
    container_name: company_api
    depends_on:
      - rabbit
    build:
      context: TestApp.CompanyApi
      dockerfile: Dockerfile
    restart: always
    networks:
      - back-tier
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://companyservice:5000
    ports:
      - "5555:5000"
  #
  user_api:
    container_name: user_api
    depends_on:
      - rabbit
    build:
      context: TestApp.UsersApi
      dockerfile: Dockerfile
    restart: always
    networks:
      - back-tier
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://userservice:5050
    ports:
      - "5555:5000"
#
networks:
  back-tier:
